### ISSUE TITLE
No feeds shown on Ubuntu 16.04 x64

### ISSUE THREAD

**Issue by digitallyamar** [Dotnaught/vulture-feeds#2]
I followed the installation and deployment commands but when I try to run the application executable "vulture-feeds-app" I only get a feed loading screen that goes on forever without any feeds being loaded. Am I missing any step? 

Attaching the screenshot of the issue I see:

![vulture_feed](https://user-images.githubusercontent.com/36293529/36625712-c10c6070-194a-11e8-853a-d771aade33e6.png)

**Comment by Dotnaught** [comment]
That's expected behavior. Select Load Defaults from the File menu. That adds several sample feeds. Or use Add Feed to specify each new feed individually. I updated the README file to clarify that.

There should be a Materialize notification that pops up to direct the user to add some feeds on first launch, but it's possible that didn't fire properly.
